baseurl = "/"
title = "Rokasporchs Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Rokasporchs Blog"
    description = "noch nicht spezifiziert, was das hier wird"
    github = "https://github.com/rokasporch"
    twitter = "https://twitter.com/rokasporch"
    email = "rokasporch@gmx.de"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
